### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Sorgrum** [cnaude/PurpleIRC#101]
I've been having some server crashes, and saw the following on a log and thought it might be PurpleIRC causing the issue. I'm on the latest build of Spigot 1.8

```
[23:05:29] [Timer-17/WARN]: Exception in thread "Timer-17" 
[23:05:29] [Timer-17/WARN]: java.lang.RuntimeException: Couldn't pause thread for message delay
[23:05:29] [Timer-17/WARN]: 	at org.pircbotx.output.OutputRaw.rawLine(OutputRaw.java:76)
[23:05:29] [Timer-17/WARN]: 	at org.pircbotx.output.OutputRaw.rawLineSplit(OutputRaw.java:129)
[23:05:29] [Timer-17/WARN]: 	at org.pircbotx.output.OutputRaw.rawLineSplit(OutputRaw.java:116)
[23:05:29] [Timer-17/WARN]: 	at org.pircbotx.output.OutputIRC.message(OutputIRC.java:138)
[23:05:29] [Timer-17/WARN]: 	at com.cnaude.purpleirc.PurpleBot.blockingIRCMessage(PurpleBot.java:448)
[23:05:29] [Timer-17/WARN]: 	at com.cnaude.purpleirc.IRCMessageQueueWatcher.queueAndSend(IRCMessageQueueWatcher.java:64)
[23:05:29] [Timer-17/WARN]: 	at com.cnaude.purpleirc.IRCMessageQueueWatcher.access$000(IRCMessageQueueWatcher.java:28)
[23:05:29] [Timer-17/WARN]: 	at com.cnaude.purpleirc.IRCMessageQueueWatcher$1.run(IRCMessageQueueWatcher.java:51)
[23:05:29] [Timer-17/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[23:05:29] [Timer-17/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
[23:05:29] [Timer-17/WARN]: Caused by: java.lang.RuntimeException: Exception encountered when writing to socket
[23:05:29] [Timer-17/WARN]: 	at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:303)
[23:05:29] [Timer-17/WARN]: 	at org.pircbotx.Utils.sendRawLineToServer(Utils.java:88)
[23:05:29] [Timer-17/WARN]: 	at org.pircbotx.output.OutputRaw.rawLine(OutputRaw.java:73)
[23:05:29] [Timer-17/WARN]: 	... 9 more
[23:05:29] [Timer-17/WARN]: Caused by: java.net.SocketException: Socket closed
[23:05:29] [Timer-17/WARN]: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
[23:05:29] [Timer-17/WARN]: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
[23:05:29] [Timer-17/WARN]: 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
[23:05:29] [Timer-17/WARN]: 	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
[23:05:29] [Timer-17/WARN]: 	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
[23:05:29] [Timer-17/WARN]: 	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
[23:05:29] [Timer-17/WARN]: 	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
[23:05:29] [Timer-17/WARN]: 	at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:300)
[23:05:29] [Timer-17/WARN]: 	... 11 more
[23:05:31] [Spigot Watchdog Thread/INFO]: Saving chunks for level 'Survival_nether'/Nether
[23:05:31] [Spigot Watchdog Thread/INFO]: Saving chunks for level 'Survival_the_end'/The End
[23:05:31] [Thread-4/INFO]: Stopping server
[23:05:31] [Thread-4/INFO]: Saving players
```

**Comment by cnaude** [comment]
Are there more errors in log? I don't think this error is the cause of the crash. It's likely the result of the server stopping abruptly.

**Comment by cnaude** [comment]
Please try build 6. http://h.cnaude.org:8081/job/PurpleIRC-spigot/6/

**Comment by Sorgrum** [comment]
Alright, I'm using build 6 now.

I think you may definitely be right. I found this in a log file: https://ghostbin.com/paste/4cdeb

**Comment by cnaude** [comment]
You might want to try the latest spigot build as well. I just ran the build tools and git-Spigot-c46583f-e6f9fd4 seems to be the latest.

**Comment by Sorgrum** [comment]
Right on! I was waiting for players to log off before doing so, but by now everyone's asleep so I'll update it now.

**Comment by Sorgrum** [comment]
I had another crash today using your reccomended build. I went through the crash report and only found a reference to PurpleIRC. The log file is: https://ghostbin.com/paste/8m6t2

**Comment by cnaude** [comment]
Please try build 7 when you have a chance. http://h.cnaude.org:8081/job/PurpleIRC-spigot/7/
How long does the server run for before it crashes?

**Comment by Sorgrum** [comment]
Alright, and just to verify, which build artifact should I use? I've noticed it takes around 16 hours or so for a crash.

**Comment by cnaude** [comment]
The build artifacts are identical.

**Comment by Sorgrum** [comment]
I think the issue had to do with a corrupted chunk in my world that kept causing the server to crash. Completely unrelated to PurpleIRC. Will wait out to see if there are any more issues and open a new issue if there is. Thanks for the help.
