### ISSUE TITLE
Partyline compatibility

### ISSUE THREAD

**Issue by RoboMWM** [cnaude/PurpleIRC#123]
I've recently added a new bot, and am having it connect to my ZNC. I wish to use the "partyline" module of the ZNC for the bot. I've have one "network" which has doesn't connect to anything for the bot's account (on the ZNC), as I guess a user needs to have a network in order to join a partyline.

However, as the bot remains loaded, this occurs every so often - I'm guessing it's attempting to get a list of users in the partyline channel, and it's failing to do so - or it's choking on the ~#channel_name syntax of the partyline channel?

The bot does successfully join the partyline and appears to be able to send messages into the channel. I have not tested sending commands, etc. to the bot yet, but I'd imagine it'd work.

```txt
[03:32:31 WARN]: org.apache.commons.lang.UnhandledException: Plugin PurpleIRC v1.0-179 generated an exception while executing task 9238 
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)                                          
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                              
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                              
        at java.lang.Thread.run(Thread.java:745)                                                                                        
Caused by: java.lang.NullPointerException: at index 0                                                                                   
        at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)                                            
        at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231)                                           
        at com.google.common.collect.ImmutableSortedSet.construct(ImmutableSortedSet.java:427)                                          
        at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:357)                                             
        at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:380)                                             
        at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:292)                                             
        at com.cnaude.purpleirc.ext.org.pircbotx.UserChannelMap.getChannels(UserChannelMap.java:77)                                     
        at com.cnaude.purpleirc.ext.org.pircbotx.UserChannelDao.getChannels(UserChannelDao.java:245)                                    
        at com.cnaude.purpleirc.ext.org.pircbotx.User.getChannels(User.java:164)                                                        
        at com.cnaude.purpleirc.PurpleBot.getChannels(PurpleBot.java:3402)                                                              
        at com.cnaude.purpleirc.PurpleBot.updateNickList(PurpleBot.java:2396)                                                           
        at com.cnaude.purpleirc.ChannelWatcher$1.run(ChannelWatcher.java:43)                                                            
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)                                                    
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)                                          
        ... 3 more
```

**Comment by cnaude** [comment]
That's an interesting problem. It appears to be an issue in the pircbotx code. I'll have to do some digging in that code.

**Comment by cnaude** [comment]
Try the latest build: https://h.cnaude.org/jenkins/job/PurpleIRC/381/

**Comment by cnaude** [comment]
I was testing znc and decided to add a new command "/irc znc ..."
https://h.cnaude.org/jenkins/job/PurpleIRC/382/

**Comment by RoboMWM** [comment]
Seems to be working, thanks! Still experimenting with partyline, but at least the bot isn't having issues anymore it seems.
