### ISSUE TITLE
Herochat legacy & v2.1.14-394 error

### ISSUE THREAD

**Issue by uncovery** [cnaude/PurpleIRC#133]
Hi, I am running spigot 1.9.4, and [herochat legacy](http://dev.bukkit.org/bukkit-plugins/herochat/files/17-herochat-legacy/) (since the 5.7 version is broken)

The latest version of PupleIRC is throwing the following error:

http://pastebin.com/enP5Adqu

All chat by users is not able to be seen on IRC, join/leave works fine.
Any idea what I can do?

thanks!

**Comment by cnaude** [comment]
Please try this version: https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/192/

**Comment by uncovery** [comment]
Thanks for the update. Seems to be the same issue:

> [13:23:34 WARN]: [PurpleIRC] Task #106 for PurpleIRC v1.0-192 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/World
        at com.cnaude.purpleirc.Utilities.NetPackets.tabPacket(NetPackets.java:156) ~[?:?]
        at com.cnaude.purpleirc.Utilities.NetPackets.addToTabList(NetPackets.java:77) ~[?:?]
        at com.cnaude.purpleirc.Utilities.NetPackets$1.run(NetPackets.java:184) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
        ... 10 more

**Comment by uncovery** [comment]
actually the chat seems to work now. I did a /irc reload and so far no errors. I am not sure what triggers the above error.

**Comment by cnaude** [comment]
The above error is related to the custom tab list. It's harmless, but does mean that the feature won't work.

**Comment by uncovery** [comment]
The latest version does not show the error anymore but chat from HErochat legacy is again not visible in IRC.

**Comment by cnaude** [comment]
The latest build is only compatible with HeroChat 5.7.x. I'm working on making it compatible with Herochat legacy.

**Comment by uncovery** [comment]
Hi there, any update on this? The latest PurpleIRC can show the "server" messages on IRC, in-game IRC chat can be read but in-game chat is not visible on IRC.

**Comment by cnaude** [comment]
For Herochat 5.7.x: https://h.cnaude.org/jenkins/job/PurpleIRC/
For Herochat 5.6.x (legacy): https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/

**Comment by uncovery** [comment]
thanks!
