### ISSUE TITLE
PremiumVanish hook exception when vanished player is joining.

### ISSUE THREAD

**Issue by Rodzynus** [cnaude/PurpleIRC#139]
When vanished player is joining the server I get this message in the console:

`[Craft Scheduler Thread - 125/WARN]: [PurpleIRC] Plugin PurpleIRC v1.0-242 generated an exception while executing task 5381311
java.lang.ClassCastException: java.util.UUID cannot be cast to java.lang.String
	at com.cnaude.purpleirc.Hooks.SuperVanishHook.isVanished(SuperVanishHook.java:47) ~[?:?]
	at com.cnaude.purpleirc.Hooks.VanishHook.isVanished(VanishHook.java:47) ~[?:?]
	at com.cnaude.purpleirc.PurpleBot.gameJoin(PurpleBot.java:1751) ~[?:?]
	at com.cnaude.purpleirc.GameListeners.GamePlayerJoinListener$1.run(GamePlayerJoinListener.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1056]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1056]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1056]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]`

It was happening on 1.10.2 version of Minecraft and it happens now on 1.11.2. Both PurpleIRC and PremiumVanish are up to date.

Haven't noticed any major issues caused by this except I can see quit message of vanished players on the IRC channel even though they're suppose to be hidden. Not sure if that's even related.

**Comment by cnaude** [comment]
Please try the latest build. https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/279/

**Comment by Rodzynus** [comment]
Latest build is working well.
Thank you very much!
